import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/landing.tsx"),
  route("dashboard", "routes/dashboard.tsx"),
  route("onboarding", "routes/onboarding/onboarding.tsx"),
  route("readyz", "routes/system/readyz.ts"),
  route("login", "routes/auth/login.ts"),
  route("signed-out", "routes/auth/signed-out.tsx"),
  route("auth/callback", "routes/auth/auth-callback.ts"),
  route("logout", "routes/auth/logout.ts"),
  route("organizations/select", "routes/workspace/select-organization.ts"),
  route("workspace/select", "routes/workspace/select-workspace.ts"),
  route("tasks", "routes/tasks/tasks.tsx"),
  route("tasks/:taskId", "routes/tasks/task-detail.tsx"),
  route("deployments", "routes/deployments/deployments.tsx"),
  route("deployments/:deploymentId", "routes/deployments/deployment-detail.tsx"),
  route("schedules", "routes/schedules/schedules.tsx"),
  route("schedules/new", "routes/schedules/new-schedule.tsx"),
  route("schedules/:scheduleId/edit", "routes/schedules/edit-schedule.tsx"),
  route("api-keys", "routes/api-keys/api-keys.tsx"),
  route("runs", "routes/runs/runs.tsx"),
  route("runs/stream", "routes/runs/runs-stream.ts"),
  route("runs/:runId/events/stream", "routes/runs/run-event-stream.ts"),
  route("runs/:runId", "routes/runs/run-detail.tsx"),
] satisfies RouteConfig;
