area:app:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/**"

area:packages:
  - changed-files:
      - any-glob-to-any-file:
          - "packages/**"

area:tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"

area:ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

area:tooling:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "pnpm-lock.yaml"
          - "pnpm-workspace.yaml"
          - "turbo.json"
          - "lefthook.yml"
          - "knip.json"
          - ".configs/**"
          - ".oxfmtrc.json"
          - ".oxlintrc.json"

area:release:
  - changed-files:
      - any-glob-to-any-file:
          - ".changeset/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "**/package.json"
          - "pnpm-lock.yaml"
