{{- if and .Values.dashboard.enabled .Values.dashboard.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cascade.fullname" . }}-dashboard
  labels:
    {{- include "cascade.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.dashboard.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.dashboard.ingress.className }}
  ingressClassName: {{ .Values.dashboard.ingress.className }}
  {{- end }}
  {{- if .Values.dashboard.ingress.tls }}
  tls:
    {{- toYaml .Values.dashboard.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.dashboard.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "cascade.fullname" $ }}-dashboard
                port:
                  number: {{ $.Values.dashboard.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
